use ratatui::style::Color;

use super::model::{Agent, Project, State, Worktree};

pub(super) fn stub() -> Vec<Project> {
    vec![
        Project {
            id: "stub-a".into(),
            name: "muse-bridge".into(),
            icon: '#',
            icon_color: Color::Cyan,
            branch: "main".into(),
            collapsed: false,
            pinned: false,
            focused: false,
            workspaces: vec![],
            directories: vec!["/projects/muse-bridge".into()],
            worktrees: vec![Worktree {
                key: "stub-a/main".into(),
                name: "main".into(),
                branch: "main".into(),
                path: "/projects/muse-bridge".into(),
                repo_root: String::new(),
                collapsed: false,
                depth: 0,
                workspace_id: "".into(),
                focused: false,
                agents: vec![
                    Agent {
                        vendor: "pi".into(),
                        label: "pi".into(),
                        title: "Implement OAuth scopes".into(),
                        state: State::Working,
                        terminal_id: "alpha".into(),
                        pane_id: "w1:p1".into(),
                        workspace_id: "".into(),
                        tab_id: "".into(),
                        cwd: "/projects/muse-bridge".into(),
                        session_ref: None,
                        seq: 0,
                        focused: false,
                    },
                    Agent {
                        vendor: "codex".into(),
                        label: "codex".into(),
                        title: "Wire retry budget".into(),
                        state: State::Done,
                        terminal_id: "beta".into(),
                        pane_id: "w1:p2".into(),
                        workspace_id: "".into(),
                        tab_id: "".into(),
                        cwd: "/projects/muse-bridge".into(),
                        session_ref: None,
                        seq: 0,
                        focused: false,
                    },
                    Agent {
                        vendor: "opencode".into(),
                        label: "opencode".into(),
                        title: "Migrate invoices table".into(),
                        state: State::Idle,
                        terminal_id: "gamma".into(),
                        pane_id: "w1:p3".into(),
                        workspace_id: "".into(),
                        tab_id: "".into(),
                        cwd: "/projects/muse-bridge".into(),
                        session_ref: None,
                        seq: 0,
                        focused: false,
                    },
                ],
            }],
        },
        Project {
            id: "stub-b".into(),
            name: "sold-by-robots".into(),
            icon: '#',
            icon_color: Color::Magenta,
            branch: "feature/mc-13200".into(),
            collapsed: false,
            pinned: false,
            focused: false,
            workspaces: vec![],
            directories: vec!["/projects/sold-by-robots".into()],
            worktrees: vec![Worktree {
                key: "stub-b/feature".into(),
                name: "sbr-9u4v.35".into(),
                branch: "feature/mc-13200".into(),
                path: "/projects/sold-by-robots".into(),
                repo_root: String::new(),
                collapsed: false,
                depth: 0,
                workspace_id: "".into(),
                focused: false,
                agents: vec![Agent {
                    vendor: "claude".into(),
                    label: "claude".into(),
                    title: "Which env file should I edit?".into(),
                    state: State::Blocked,
                    terminal_id: "delta".into(),
                    pane_id: "w2:p1".into(),
                    workspace_id: "".into(),
                    tab_id: "".into(),
                    cwd: "/projects/sold-by-robots".into(),
                    session_ref: None,
                    seq: 0,
                    focused: false,
                }],
            }],
        },
    ]
}
